# 基本设置
title: AiuYH8 Crypto Hub
SEOTitle: AiuYH8 Crypto Hub - 实时加密货币价格追踪与分析
description: "深度解析加密货币市场动态，提供Pi Network、比特币、以太坊等数字资产实时价格转换，专注USDT汇率、区块链钱包与DeFi生态系统研究。"
keyword: "pi to pkr, 比特币行情, pi network price, pengu usdt, bera usdt, btc价格, doge explorer, bitcoin to php, sol usdt, 特朗普币价格, memefi premium, xrp whale activity, xrp to php, eth to usd, usdt to vnd, pi value crypto, usdt to pkr today, 比特币实时价格美元, pepe investment, okx wallet verification, usd to bnb, pi coin value"
url: "https://aiuyh8.github.io"
baseurl: ""
github_username:    aiuyh8
header-img: img/post-bg-desk.jpg

# 构建设置
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 10

# 插件
plugins:
  - jekyll-paginate

# 排除文件
exclude:
  - README.md
  - Gruntfile.js
  - package.json
  - node_modules
  - less
